<?php

$config->custom->debug['level'] = 255;
$config->custom->debug['syslog'] = true;
$config->custom->session['blowfish'] = '************************';  # Autogenerated for pla
$config->custom->appearance['friendly_attrs'] = array(
        'gid'                      => 'Group',
        'mail'                     => 'Email',
        'uid'                      => 'User Name',
        'userPassword'             => 'Password'
);

$servers = new Datastore();
$servers->newServer('ldap_pla');
$servers->setValue('server','name','LDAP Server Name');
$servers->setValue('server','host','ldaps://<server-hostname-matching-the-fqdn-on-ldap-cacert-pem:636');
$servers->setValue('server','port',0);
$servers->setValue('server','base',array('dc=example,dc=com'));
$servers->setValue('login','auth_type','cookie');
$config->custom->appearance['hide_template_warning'] = true;
$servers->setValue('server','tls',false);
$servers->setValue('server','tls_cacert','/etc/ssl/certs/ldap-cacert.pem');
putenv('LDAPTLS_CACERT=/etc/ssl/certs/ldap-cacert.pem');
ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);
$servers->setValue('login','anon_bind',false);
$servers->setValue('login','timeout',30);
$config->custom->session['reCAPTCHA-enable'] = false;

?>
